baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

theme = 'papermod'

[params]
disableThemeToggle = true
defaultTheme = "dark"

[params.regularMode]
enabled = false

[params.profileMode]
enabled = true

[[params.socialIcons]]
name = "github"
url = "https://github.com/m1dugh"
